### ISSUE TITLE
Desktop Version throws Exception on Mousemove 

### ISSUE THREAD

**Issue by wayoda** [codeschluss/wupportal#105]
´´´
unhandledError: Error
Time:
2019-10-07T15:03:30.999Z
Status:
NaN
Resource:
/
Exception:
Uncaught (in promise): TypeError: e.forEach is not a function
TypeError: e.forEach is not a function
    at sr (https://www.wupportal.org/vendor.js:1:595177)
    at co (https://www.wupportal.org/vendor.js:1:611289)
    at Object.oo (https://www.wupportal.org/vendor.js:1:611122)
    at Module.Mjfc (https://www.wupportal.org/11.js:1:1138)
    at i (https://www.wupportal.org/runtime.js:1:552)
    at t.invoke (https://www.wupportal.org/polyfills.js:1:9304)
    at Object.onInvoke (https://www.wupportal.org/vendor.js:1:622360)
    at t.invoke (https://www.wupportal.org/polyfills.js:1:9244)
    at e.run (https://www.wupportal.org/polyfills.js:1:4507)
    at https://www.wupportal.org/polyfills.js:1:16310
Stacktrace:
Error: Uncaught (in promise): TypeError: e.forEach is not a function
TypeError: e.forEach is not a function
    at sr (https://www.wupportal.org/vendor.js:1:595177)
    at co (https://www.wupportal.org/vendor.js:1:611289)
    at Object.oo (https://www.wupportal.org/vendor.js:1:611122)
    at Module.Mjfc (https://www.wupportal.org/11.js:1:1138)
    at i (https://www.wupportal.org/runtime.js:1:552)
    at t.invoke (https://www.wupportal.org/polyfills.js:1:9304)
    at Object.onInvoke (https://www.wupportal.org/vendor.js:1:622360)
    at t.invoke (https://www.wupportal.org/polyfills.js:1:9244)
    at e.run (https://www.wupportal.org/polyfills.js:1:4507)
    at https://www.wupportal.org/polyfills.js:1:16310
    at P (https://www.wupportal.org/polyfills.js:1:15559)
    at P (https://www.wupportal.org/polyfills.js:1:15117)
    at https://www.wupportal.org/polyfills.js:1:16347
    at t.invokeTask (https://www.wupportal.org/polyfills.js:1:9988)
    at Object.onInvokeTask (https://www.wupportal.org/vendor.js:1:622272)
    at t.invokeTask (https://www.wupportal.org/polyfills.js:1:9909)
    at e.runTask (https://www.wupportal.org/polyfills.js:1:5170)
    at g (https://www.wupportal.org/polyfills.js:1:12255)
´´´

**Comment by schlusslicht** [comment]
This issue is fixed with 3da53e5f80c00e1e339fd51237cb2ffe676955f9.
